<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Conf' => $baseDir . '/class/conf.php',
    'FB_Group' => $baseDir . '/class/fbgroup.php',
    'View' => $baseDir . '/class/view.php',
);
